### ISSUE TITLE
user_playlist_create creates a public playlist despite setting the public parameter to False

### ISSUE THREAD

**Issue by ShevinuM** [spotipy-dev/spotipy#1072]
I am trying to get my code to create a private playlist but despite setting `public=False`, the playlist being created is public.

`playlist = object.user_playlist_create(user_id, playlist_name, public=False, collaborative=False, description=f"My liked songs for {playlist_name}")`

**Expected behavior**

**Output**
Paste and format errors (with complete stacktrace) or logs. Make sure to remove sensitive information.

**Environment:**
 - OS: Mac
 - Python version: 3.11.3
 - spotipy version: 2.23.0
 - IDE: Visual Studio Code

**Comment by dieser-niko** [comment]
Tbh I have had problems myself when trying to create/modify a playlist in terms of visibility. I hope you mean the same thing as me when you say "private playlist".

The problem here is that it's not possible because the Spotify API doesn't have that kind of attribute to set a playlist to private. You can only unlist it with `public=False` and that's it.

This is not a "bug" introduced by spotipy.

**Comment by ShevinuM** [comment]
Isn't public=False supposed to set a playlist to private?

**Comment by dieser-niko** [comment]
As far as I know this will only affect the playlists visibility on your profile
