### ISSUE TITLE
Dots in artists names

### ISSUE THREAD

**Issue by borja190898** [spotipy-dev/spotipy#1079]
Hello, when I try to search for an artist by name and the name has dots or strange characters (for example C.R.O), it does not find it and detects it as if it were a different one.
How could this be avoided?
Thank you

**Comment by borja190898** [comment]
Anyone know any solution?
Thanks

**Comment by dieser-niko** [comment]
I'm not at home currently but one thing to try out would be to use alphanumeric characters only. So instead of C.R.O. just CRO

And also I just tested what would happen when I search the artist and found out that he actually calls himself CRO on spotify. It's just CRO either way. But still, it seems that the application doesn't seem to have that problem.

I'll look into this as soon as possible.

**Comment by Voltaic314** [comment]
I don't think this really needs fixing necessarily because some artists do actually have certain characters in their spotify names. Like "S. Carey" for example. But you could try to do a recursive search where it searches what the user wants and then if no results show then try without the characters for example maybe.

**Comment by itsbekas** [comment]
> Hello, when I try to search for an artist by name and the name has dots or strange characters (for example C.R.O), it does not find it and detects it as if it were a different one. How could this be avoided? Thank you

Hey, can you show us how you tried to search for this artist? I just tested the following snippet with the artist you used as an example:

```python
s = Spotify(client_credentials_manager=SpotifyClientCredentials())
cro = s.search('C.R.O', type='artist')
data = cro['artists']['items'][0]['name']
print(data)
```
and the output was, as expected:
```
C.R.O
```

**Comment by dieser-niko** [comment]
@borja190898 any updates so far? Could you post a code snippet?

**Comment by stephanebruckert** [comment]
Closing as this seems to work and no snippet was provided
