### ISSUE TITLE
The followers field in the current_user is empty

### ISSUE THREAD

**Issue by Mews** [spotipy-dev/spotipy#1095]
I'm trying to get a list of the users that follow me, however, the `followers` field in the data returned by `current_user()` only shows the number of users that follow me, but not which users.
This is the code I'm using (`CLIENT_ID` and `CLIENT_SECRET` are defined earlier in the code)
```python
import spotipy
from spotipy.oauth2 import SpotifyOAuth

sp = spotipy.Spotify(auth_manager=SpotifyOAuth(scope="user-follow-read", client_id=CLIENT_ID, client_secret=CLIENT_SECRET, redirect_uri="http://localhost:8888/callback"))

print(sp.current_user()["followers"])
```
From what I could tell from the spotify api docs I'm using the correct scope, but this code always prints `{'href': None, 'total': 10}`
Is there a way to get what users follow me?

**Comment by dieser-niko** [comment]
A quick Google search turned up [this Stackoverflow answer](https://stackoverflow.com/a/24309048) from a supposed Spotify employee, suggesting that Spotify has known since 2014 that this has been a long-awaited addition to the API, but has apparently made no progress.

There's a somewhat unofficial way, but using this would technically be against [Spotify's Developer Terms](https://developer.spotify.com/terms), it is also outside of the boundaries of spotipy and may be unreliable since there's no official documentation for this particular endpoint.

This would require an additional package called `spotipy_anon` which allows you to use a token that is intended for the web UI.

Then you can do something like this:

```python3
from spotipy.cache_handler import MemoryCacheHandler
from spotipy_anon import SpotifyAnon
import requests

auth_manager = SpotifyAnon(cache_handler=MemoryCacheHandler())
session = requests.Session()

def get_user_followers(user: str, proxies = None, requests_timeout=5):
    headers = {"Authorization": "Bearer {0}".format(auth_manager.get_access_token(as_dict=False)), 
               "Content-Type": "application/json"}
    response  = session.get(
        f"https://spclient.wg.spotify.com/user-profile-view/v3/profile/{user}/followers",
        headers=headers, proxies=proxies, timeout=requests_timeout
    )
    response.raise_for_status()
    return response.json()

for follower in get_user_followers("spotify")["profiles"]:
    print(follower["name"])
```

You might notice that there's no escaping for the username whatsoever, so use it at your own risk. Spotify itself hasn't specified what can and can't be inside a user ID (https://developer.spotify.com/documentation/web-api/concepts/spotify-uris-ids), but my guess would be alphanumeric characters, so a simple str.isalnum() should do the trick.

**Comment by Mews** [comment]
What do you mean by there's no escaping for the username?

**Comment by Mews** [comment]
At any rate this does work thank you so much

**Comment by dieser-niko** [comment]
> What do you mean by there's no escaping for the username?

Escaping is mostly a method used in SQL queries. I found a Stackoverflow answer which explains the process of escaping pretty good: https://stackoverflow.com/a/10646166

Obviously we're not using SQL here, but the principle stays the same. For example, if you host a web app and a user tries to enter a username like "@malicious-website.com", the request might go to malicious-website.com instead of spotify.com. But to be honest, I'm not up to date with URL injections (and this example didn't even work when I tested it), but I hope you can see where I'm going with this.

> Also why would this not be allowed by the tos?

Check section IV of the developer terms, I assume the usage of my script would violate at least one of these terms.

**Comment by Mews** [comment]
Oh ok but is escaping really necessary then? The `get_user_followers` function you wrote expects a user id so it should be fine no?

**Comment by dieser-niko** [comment]
Just because the argument is `user: str` doesn't mean it only accepts usernames. But I've updated the code snippet to include a check for alphanumeric characters just to make sure.

**Comment by Mews** [comment]
But you're meant to pass a user id to it no? At least thats what worked for me

**Comment by dieser-niko** [comment]
Yes, but as I said, this depends on the usecase. If you're building a web app that asks for a user ID, then you could end up with an invalid ID very fast.

**Comment by Mews** [comment]
Alright anyway your solution fixed it tysm
