### ISSUE TITLE
All Spotipy exceptions should inherit from SpotifyException

### ISSUE THREAD

**Issue by vitorbaptista** [spotipy-dev/spotipy#1160]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to catch any exceptions raised by Spotipy. I thought this was what `spotipy.client.SpotifyException` was for, but `spotipy.oauth2.SpotifyOauthError` inherits from Python's base `Exception`.

**Describe the solution you'd like**

If I catch `spotipy.client.SpotifyException` I should catch all exceptions raised by Spotipy.

**Describe alternatives you've considered**

Explicitly using `except (spotipy.client.SpotifyException, spotipy.oauth2.SpotifyOauthError) as e`. This works, but feels a bit too coupled.

**Comment by dieser-niko** [comment]
@stephanebruckert any objections? Otherwise I would just start working on a PR.
I don't see any reason why it should stay this way.

Currently there are 3 exception classes:

- `exceptions.SpotifyException`/`client.SpotifyException`
- oauth2.SpotifyOauthError
- oauth2.SpotifyStateError

As a change, I would suggest adding a new exception called `SpotifyBaseException` with no specific attributes, as the `SpotifyOauthError` doesn't share any attributes with `SpotifyException`.

Also while we're at it, I would move the errors from `oauth2.py` to the already existing `exceptions.py` file, because they don't need any imports.

**Comment by dieser-niko** [comment]
I've created a PR, you can try it out by adding this to your `requirements.txt` file:
```
git+https://github.com/spotipy-dev/spotipy@1160-move-exceptions
```

I've implemented it like I've described in my last comment.
